apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops-w-kube
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
           claimName: log-output-pvc
      containers:
        - name: writer
          image: j0ne/log_output:writer-latest-10.9
          volumeMounts: # Mount volume
          - name: shared-logs
            mountPath: /usr/src/files
          readinessProbe:
            initialDelaySeconds: 15 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
              path: /healthz
              port: 3005
        - name: reader
          image: j0ne/log_output:reader-latest
          volumeMounts: # Mount volume
          - name: shared-logs
            mountPath: /usr/src/files
        # - name: pingpong
        #   image: j0ne/pingpong:write-latest-3
        #   volumeMounts: # Mount volume
        #   - name: shared-logs
        #     mountPath: /usr/src/files

