apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops-w-kube
  name: log-output-claim
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi